### ISSUE TITLE
language tags missing ion ConceptScheme descriptions in 008 vocabularies

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd_vocabs_marc_006_008#12]
When there are literal values describing the skos:ConceptScheme, language tags were not included. Insert those tags at the same time provenance statement are repoaired (see issue #11 ). The skosLConcept instance descriptions did include language tags and are ok in that regard.

**Comment by dkreisstomkins** [comment]
This was my oversight.  Sorry!

**Comment by gerontakos** [comment]
These are fine!
