### ISSUE TITLE
related identifiers in DataCite metadata have incorrect relationType

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd_vocabs_marc_006_008#13]
The triple using the property dct:source in the rdfxml should have been assigned an attribute value in the DataCite metadata; specifically: relatedIdentifiers/relatedIdentifier/@relationType="isDerivedFrom"; instead, it was assigned the attribute value relatedIdentifiers/relatedIdentifier/@relationType="isSourceOf". This happened for all 008 vocabularies. The description would need to be repaired in DataCite.

**Comment by cspayne** [comment]
This has been corrected in the uwlswd/DataCite XML files using uwlswd/py/datacite_metadata.py.
Metadata in DataCite has been updated.
