### ISSUE TITLE
006: remove incorrect dct:hasFormat triples

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd_vocabs_marc_006_008#16]
incorrect dct:hasFormat triples (in the 006 only) should be removed from the RDF/XML and the script that produces the alternative formats should be re-run on that rdf/xml so that these triples are removed from all serializations. dct:hasFormat should only point toward actual datasets, not to W3C IRIs that identify the format itself.

**Comment by gerontakos** [comment]
Changed 006/form_of_material.rdf so that all 4 erroneous dct:hasFormat triples were removed. Version number changed to 1-1-0. However, the derivative serializations are still the old version and need to be created from form_of_material.rdf, so this issue will remain open.

**Comment by gerontakos** [comment]
Used oXygen to join-and-normalize-lines in the RDF/XML. Issue still open.

**Comment by cspayne** [comment]
All serializations are now up-to-date - see [commit](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/commit/387296acb0fc8509deebaf732b266af4f1492c5e)
