### ISSUE TITLE
We do not need language tabs for values of skos:notation properties.

### ISSUE THREAD

**Issue by dkreisstomkins** [uwlib-cams/uwlswd_vocabs_marc_006_008#18]
<https://doi.org/10.6069/uwlswd.f447-ax91#h> a skos:Concept ;
    skos:definition "Humorous work, satire, or of similar literary form."@en ;
    skos:inScheme <https://doi.org/10.6069/uwlswd.f447-ax91> ;
    skos:notation "h"_@en_ ;
    skos:prefLabel "humor, satires, etc."@en .

**Comment by gerontakos** [comment]
Repaired for 006/form_of_material.rdf. Reserializations must still take place but the main file has been changed. Version number changed to 1-1-1. Change still required for all 008/ files.
