### ISSUE TITLE
repair "none of the following" in "Continuing: form of original item"

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd_vocabs_marc_006_008#21]
In the vocabulary "Continuing: form of original item" i.e. https://doi.org/10.6069/uwlswd.42d2-ca58, the IRI for the concept "none of the following" was rendered as https://doi.org/10.6069/uwlswd.42d2-ca58pound but it should have been https://doi.org/10.6069/uwlswd.42d2-ca58#pound. @gerontakos should repair this

**Comment by cspayne** [comment]
I corrected this in order to run the serialization script!

**Comment by gerontakos** [comment]
Oh thank you!
