### ISSUE TITLE
finish main.py workflow for two new 'nature of contents' concept schemes

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_vocabs_marc_006_008#26]
@dkreisstomkins the error with main.py was caused by incorrect data in the RDF/XML for new concept scheme 'books: nature of contents' - see [details of changes which resolved the error](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/commit/2742e50b237cd43d13e338915842a9528826e642).

My best understanding without revisiting main.py code or stylesheets is that the incorrect `dct:hasFormat` values in the RDF/XML -- pointing to a directory and files which don't exist, caused the main.py transformation error. In any case making the change (link to commit just above) resolved the error and allowed me to run main.py successfully for **books_nature_of_contents/**.

I believe that if you make similar edits to **continuing_nature_of_contents/continuing_nature_of_contents.rdf** (see [L97-100](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/blob/d294a76b74211108e6e0e30ef3e488a7cae5cf22/008/continuing_nature_of_contents/continuing_nature_of_contents.rdf#L97-L100)), you'll be able to run main.py successfully and then we can make the pull request.

My understanding, to confirm with @cspayne if possible:

**main.py works ✔️ in both of the following scenarios:**
- A new resource (RDF/XML serialization) is processed using main.py and includes *no* `dct:hasFormat` triples
- An updated resource (RDF/XML serialization) is processed using main.py and includes *accurate* `dct:hasFormat` triples (filepath/filenames point to the other serializations of the resource, which will be overwritten by main.py processing to reflect updates in RDF/XML)

**main.py does not work ❌ in the following scenario:**
- An updated resource (RDF/XML serialization) is processed using main.py and includes *incorrect* `dct:hasFormat` triples (filepath/filenames do not point to the current location of other serializations of the resource)

⚡ **_action items_**

- [x] @dkreisstomkins makes corrections to continuing_nature_of_contents.rdf as were made for books_nature_of_contents.rdf (see [details of changes which resolved the error](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/commit/2742e50b237cd43d13e338915842a9528826e642))
- [x] @dkreisstomkins commits these changes
- [x] @dkreisstomkins runs main.py for continuing_nature_of_contents
- [x] If successful, @dkreisstomkins commits serializations for continuing_nature_of_contens
- [ ] At next meeting @dkreisstomkins and @briesenberg07 walk through pull request for branch 'divide_somes' (books_nature_of_contents and continuing_nature_of_contents)

**Comment by briesenberg07** [comment]
@dkreisstomkins the other thing is to make sure you know that I've made two commits to the divide_somes branch and you need to pull before you tackle the action items above (I'm sure you would've anyway but wanted to be extra sure!) TY!

**Comment by cspayne** [comment]
> **main.py works ✔️ in both of the following scenarios:**
> 
>* A new resource (RDF/XML serialization) is processed using main.py and includes _no_ `dct:hasFormat` triples
> 
> * An updated resource (RDF/XML serialization) is processed using main.py and includes _accurate_ `dct:hasFormat` triples (filepath/filenames point to the other serializations of the resource, which will be overwritten by main.py processing to reflect updates in RDF/XML)
> 
> 
> **main.py does not work ❌ in the following scenario:**
> 
> * An updated resource (RDF/XML serialization) is processed using main.py and includes _incorrect_ `dct:hasFormat` triples (filepath/filenames do not point to the current location of other serializations of the resource)

That's correct! I never implemented a function to delete incorrect dct:hasFormat triples...do we want one? It would be fairly simple to do.

**Comment by briesenberg07** [comment]
Thank you @cspayne !

> a function to delete incorrect dct:hasFormat triples

Would this compare the file path input from the terminal with the filepath in `dct:hasFormat` triples to remove/replace incorrect dct:hasFormat triples?

**Comment by cspayne** [comment]
@briesenberg07 
> Would this compare the file path input from the terminal with the filepath in `dct:hasFormat` triples to remove/replace incorrect dct:hasFormat triples?

It would likely be the simplest to delete all dct:hasFormat triples before the correct ones are added, which is easy to do with rdflib.

**Comment by briesenberg07** [comment]
We are deciding *not* to make any changes to main.py/serialize.py at this time. So the important things to remember when processing RDF/XML with main.py are:

📢  _**Cannot pass incorrect dct:hasFormat paths to main.py!!**_  
**YOU CAN:**
- Pass RDF/XML will *correct* dct:hasFormat triples
- Pass RDF/XML with *no* dct:hasFormat triples
