### ISSUE TITLE
Obsolete values

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd_vocabs_marc_006_008#8]
- Extract the values we use in spreadsheets.
    - Theo should create this list and pass to David.
- The rough plan: Only create entries in the 008 vocabularies for obsolete values used in the m2r mapping.
- However, retain obsolete values inherited in the vocabularies from the OMR.
- More specifically: anything with status = ?, START HERE, or reviewed should have an entry in our vocabularies; whereas anything with status = delete, or not mapped can be omitted.
- Statement (can be added to m2r documentation): if someone needs those omitted obsolete values they can extend our vocabulary.

**Comment by gerontakos** [comment]
### Below is a list of all 008 obsolete values followed by their status in the m2r mapping
code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = g
status: ?

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = g
status: ?

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = h
status: ?

code Value label: Multimedia [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = i
status: ?

code Value label: Handwritten transcript [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = j
status: ?

code Value label: Photocopy [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = p
status: ?

code Value label: Typewritten transcript [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = t
status: ?

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = z
status: ?

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (MUSIC) = h
status: ?

code Value label: Government publication--level undetermined [OBSOLETE]
position: 008/28 (VISUAL MATERIALS) = n
status: ?

code Value label: Negative photocopy [OBSOLETE]
position: 008/33-34 (MAPS) = c
status: START HERE

code Value label: Legal cases and case notes [OBSOLETE]
position: 008/24 (CONTINUING RESOURCES) = n
status: delete

code Value label: Legal cases and case notes [OBSOLETE]
position: 008/25-27 (CONTINUING RESOURCES) = n
status: delete

code Value label: Color [OBSOLETE]
position: 008/18-21 (MAPS) = h
status: delete

code Value label: Photocopy, blue line print [OBSOLETE]
position: 008/33-34 (MAPS) = a
status: delete

code Value label: Photocopy [OBSOLETE]
position: 008/33-34 (MAPS) = b
status: delete

code Value label: Actual date and copyright date [OBSOLETE]
position: 008/06 (ALL MATERIALS) = c
status: not mapped

code Value label: Detailed date [OBSOLETE]
position: 008/06 (ALL MATERIALS) = d
status: not mapped

code Value label: National Agricultural Library [OBSOLETE]
position: 008/39 (ALL MATERIALS) = a
status: not mapped

code Value label: National Library of Medicine [OBSOLETE]
position: 008/39 (ALL MATERIALS) = b
status: not mapped

code Value label: Report to [OBSOLETE]
position: 008/39 (ALL MATERIALS) = n
status: not mapped

code Value label: Comic strips [OBSOLETE]
position: 008/33 (BOOKS) = c
status: not mapped

code Value label: Australia [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 3
status: not mapped

code Value label: Moscow Regional Centre [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 5
status: not mapped

code Value label: Federal Republic of Germany [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 6
status: not mapped

code Value label: France [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 7
status: not mapped

code Value label: Argentina [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 8
status: not mapped

code Value label: Japan [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 9
status: not mapped

code Value label: Unknown [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = u
status: not mapped

code Value label: Punched paper tape [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = g
status: not mapped

code Value label: Magnetic tape [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = h
status: not mapped

code Value label: Multimedia [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = i
status: not mapped

code Value label: Other physical medium [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = x
status: not mapped

code Value label: Other physical medium [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = z
status: not mapped

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = z
status: not mapped

code Value label: Other [OBSOLETE]
position: 008/24 (MAPS) = h
status: not mapped

code Value label: Film negative [OBSOLETE]
position: 008/33-34 (MAPS) = d
status: not mapped

code Value label: Facsimile [OBSOLETE]
position: 008/33-34 (MAPS) = f
status: not mapped

code Value label: Relief model [OBSOLETE]
position: 008/33-34 (MAPS) = g
status: not mapped

code Value label: Rare [OBSOLETE]
position: 008/33-34 (MAPS) = h
status: not mapped

code Value label: Braille [OBSOLETE]
position: 008/33-34 (MAPS) = m
status: not mapped

code Value label: Large print [OBSOLETE]
position: 008/33-34 (MAPS) = q
status: not mapped

code Value label: Multimedia [OBSOLETE]
position: 008/23 (MUSIC) = i
status: not mapped

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (MUSIC) = x
status: not mapped

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (MUSIC) = z
status: not mapped

code Value label: Historical information other than music [OBSOLETE]
position: 008/24-29 (MUSIC) = j
status: not mapped

code Value label: Not applicable [OBSOLETE]
position: 008/24-29 (MUSIC) = n
status: not mapped

code Value label: No [OBSOLETE]
position: 008/23-27 (VISUAL MATERIALS) = 0
status: not mapped

code Value label: Yes [OBSOLETE]
position: 008/23-27 (VISUAL MATERIALS) = 1
status: not mapped

code Value label: Electronic videorecording [OBSOLETE]
position: 008/33 (VISUAL MATERIALS) = e
status: not mapped

code Value label: Not applicable [OBSOLETE]
position: 008/34 (VISUAL MATERIALS) = #
status: not mapped

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (BOOKS) = g
status: reviewed

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (BOOKS) = g
status: reviewed

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (BOOKS) = h
status: reviewed

code Value label: Multimedia [OBSOLETE]
position: 008/23 (BOOKS) = i
status: reviewed

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (BOOKS) = z
status: reviewed

code Value label: Handbooks [OBSOLETE]
position: 008/24-27 (BOOKS) = h
status: reviewed

code Value label: Technical reports [OBSOLETE]
position: 008/24-27 (BOOKS) = x
status: reviewed

code Value label: Government publication--level undetermined [OBSOLETE]
position: 008/28 (BOOKS) = n
status: reviewed

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = g
status: reviewed

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = g
status: reviewed

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = h
status: reviewed

code Value label: Multimedia [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = i
status: reviewed

code Value label: Technical reports [OBSOLETE]
position: 008/25-27 (CONTINUING RESOURCES) = x
status: reviewed

code Value label: Government publication--level undetermined [OBSOLETE]
position: 008/28 (CONTINUING RESOURCES) = n
status: reviewed

code Value label: Color [OBSOLETE]
position: 008/18-21 (MAPS) = h
status: reviewed

code Value label: Photocopy, blue line print [OBSOLETE]
position: 008/33-34 (MAPS) = a
status: reviewed

code Value label: Photocopy [OBSOLETE]
position: 008/33-34 (MAPS) = b
status: reviewed

**Comment by gerontakos** [comment]
there's only like 70, let's just do them all!

**Comment by CECSpecialistI** [comment]
> there's only like 70, let's just do them all!

Huzzah!

**Comment by dkreisstomkins** [comment]
All are now entered except for 15 which don't have vocabularies present in the OMR translation to xml.  They are listed below.

(Two of these values have a spot in 007 vocabularies which I believe should be moved to 008 to match the LoC MARC standard arrangement.  This leaves 13 obsolete values without vocabularies.  4 new vocabularies would accommodate them.)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/david/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/david/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



code   Value label: National Agricultural Library [OBSOLETE] | needs new vocabulary? 39=Cataloging Source
-- | --
position:   008/39 (ALL MATERIALS) = a |  
status:   not mapped |  
code   Value label: National Library of Medicine [OBSOLETE] | needs new vocabulary? 39=Cataloging Source
position:   008/39 (ALL MATERIALS) = b |  
status:   not mapped |  
code   Value label: Report to [OBSOLETE] | needs new vocabulary? 39=Cataloging Source
position:   008/39 (ALL MATERIALS) = n |  
status:   not mapped |  
code   Value label: Australia [OBSOLETE] | needs new vocabulary? 20=Undefined
position:   008/20 (CONTINUING RESOURCES) = 3 |  
status:   not mapped |  
code   Value label: Moscow Regional Centre [OBSOLETE] | needs new vocabulary? 20=Undefined
position:   008/20 (CONTINUING RESOURCES) = 5 |  
status:   not mapped |  
code   Value label: Federal Republic of Germany [OBSOLETE] | needs new vocabulary? 20=Undefined
position:   008/20 (CONTINUING RESOURCES) = 6 |  
status:   not mapped |  
code   Value label: France [OBSOLETE] | needs new vocabulary? 20=Undefined
position:   008/20 (CONTINUING RESOURCES) = 7 |  
status:   not mapped |  
code   Value label: Argentina [OBSOLETE] | needs new vocabulary? 20=Undefined
position:   008/20 (CONTINUING RESOURCES) = 8 |  
status:   not mapped |  
code   Value label: Japan [OBSOLETE] | needs new vocabulary? 20=Undefined
position:   008/20 (CONTINUING RESOURCES) = 9 |  
status:   not mapped |  
code   Value label: Unknown [OBSOLETE] | needs new vocabulary? 20=Undefined
position:   008/20 (CONTINUING RESOURCES) = u |  
status:   not mapped |  
code   Value label: Other [OBSOLETE] | needs new vocabulary?  24=Undefined
position:   008/24 (MAPS) = h |  
status:   not mapped |  
code   Value label: No [OBSOLETE] | needs new vocabulary? 23-27=Undefined
position:   008/23-27 (VISUAL MATERIALS) = 0 |  
status:   not mapped |  
code   Value label: Yes [OBSOLETE] | needs new vocabulary? 23-27=Undefined
position:   008/23-27 (VISUAL MATERIALS) = 1 |  
status:   not mapped |  
code   Value label: Electronic videorecording [OBSOLETE] | needs new vocabulary? 33=Type of Visual Material
position:   008/33 (VISUAL MATERIALS) = e |  
status:   not mapped |  
code   Value label: Not applicable [OBSOLETE] | needs new vocabulary? 34=Technique
position:   008/34 (VISUAL MATERIALS) = # |  
status:   not mapped |  



</body>

</html>

**Comment by gerontakos** [comment]
Oof, I failed to search the CharacterPositionLabel label so here's a more accurate and much longer list (almost 200 values instead of about 70):
Below is a list of all 008 obsolete values followed by their status in the m2r mapping
code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = g
status: ?

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = g
status: ?

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = h
status: ?

code Value label: Multimedia [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = i
status: ?

code Value label: Handwritten transcript [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = j
status: ?

code Value label: Photocopy [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = p
status: ?

code Value label: Typewritten transcript [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = t
status: ?

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (MIXED MATERIALS) = z
status: ?

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (MUSIC) = h
status: ?

code Value label: Government publication--level undetermined [OBSOLETE]
position: 008/28 (VISUAL MATERIALS) = n
status: ?

code Value label: Negative photocopy [OBSOLETE]
position: 008/33-34 (MAPS) = c
status: START HERE

code Value label: Legal cases and case notes [OBSOLETE]
position: 008/24 (CONTINUING RESOURCES) = n
status: delete

code Value label: Legal cases and case notes [OBSOLETE]
position: 008/25-27 (CONTINUING RESOURCES) = n
status: delete

code Value label: Color [OBSOLETE]
position: 008/18-21 (MAPS) = h
status: delete

code Value label: Photocopy, blue line print [OBSOLETE]
position: 008/33-34 (MAPS) = a
status: delete

code Value label: Photocopy [OBSOLETE]
position: 008/33-34 (MAPS) = b
status: delete

code Value label: Actual date and copyright date [OBSOLETE]
position: 008/06 (ALL MATERIALS) = c
status: not mapped

code Value label: Detailed date [OBSOLETE]
position: 008/06 (ALL MATERIALS) = d
status: not mapped

code Value label: National Agricultural Library [OBSOLETE]
position: 008/39 (ALL MATERIALS) = a
status: not mapped

code Value label: National Library of Medicine [OBSOLETE]
position: 008/39 (ALL MATERIALS) = b
status: not mapped

code Value label: Report to [OBSOLETE]
position: 008/39 (ALL MATERIALS) = n
status: not mapped

code Value label: No attempt to code
position: 008/32 (BOOKS) = |
status: not mapped

code Value label: Main entry not in body of entry
position: 008/32 (BOOKS) = 0
status: not mapped

code Value label: Main entry in body of entry
position: 008/32 (BOOKS) = 1
status: not mapped

code Value label: Comic strips [OBSOLETE]
position: 008/33 (BOOKS) = c
status: not mapped

code Value label: No determinable frequency
position: 008/18 (COMPUTER FILES) = #
status: not mapped

code Value label: Annual
position: 008/18 (COMPUTER FILES) = a
status: not mapped

code Value label: Bimonthly
position: 008/18 (COMPUTER FILES) = b
status: not mapped

code Value label: Semiweekly
position: 008/18 (COMPUTER FILES) = c
status: not mapped

code Value label: Daily
position: 008/18 (COMPUTER FILES) = d
status: not mapped

code Value label: Biweekly
position: 008/18 (COMPUTER FILES) = e
status: not mapped

code Value label: Semiannual
position: 008/18 (COMPUTER FILES) = f
status: not mapped

code Value label: Biennial
position: 008/18 (COMPUTER FILES) = g
status: not mapped

code Value label: Triennial
position: 008/18 (COMPUTER FILES) = h
status: not mapped

code Value label: Three times a week
position: 008/18 (COMPUTER FILES) = i
status: not mapped

code Value label: Three times a month
position: 008/18 (COMPUTER FILES) = j
status: not mapped

code Value label: Monthly
position: 008/18 (COMPUTER FILES) = m
status: not mapped

code Value label: Not applicable
position: 008/18 (COMPUTER FILES) = n
status: not mapped

code Value label: Quarterly
position: 008/18 (COMPUTER FILES) = q
status: not mapped

code Value label: Semimonthly
position: 008/18 (COMPUTER FILES) = s
status: not mapped

code Value label: Three times a year
position: 008/18 (COMPUTER FILES) = t
status: not mapped

code Value label: Unknown
position: 008/18 (COMPUTER FILES) = u
status: not mapped

code Value label: Weekly
position: 008/18 (COMPUTER FILES) = w
status: not mapped

code Value label: Other frequencies
position: 008/18 (COMPUTER FILES) = z
status: not mapped

code Value label: Not applicable
position: 008/19 (COMPUTER FILES) = #
status: not mapped

code Value label: Normalized irregular
position: 008/19 (COMPUTER FILES) = n
status: not mapped

code Value label: Regular
position: 008/19 (COMPUTER FILES) = r
status: not mapped

code Value label: Unknown
position: 008/19 (COMPUTER FILES) = u
status: not mapped

code Value label: Completely irregular
position: 008/19 (COMPUTER FILES) = x
status: not mapped

code Value label: Computer readable
position: 008/27 (COMPUTER FILES) = a
status: not mapped

code Value label: Other
position: 008/27 (COMPUTER FILES) = z
status: not mapped

code Value label: No ISSN center code assigned
position: 008/20 (CONTINUING RESOURCES) = #
status: not mapped

code Value label: No attempt to code
position: 008/20 (CONTINUING RESOURCES) = |
status: not mapped

code Value label: International Center
position: 008/20 (CONTINUING RESOURCES) = 0
status: not mapped

code Value label: United States
position: 008/20 (CONTINUING RESOURCES) = 1
status: not mapped

code Value label: United Kingdom
position: 008/20 (CONTINUING RESOURCES) = 2
status: not mapped

code Value label: Australia [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 3
status: not mapped

code Value label: Canada
position: 008/20 (CONTINUING RESOURCES) = 4
status: not mapped

code Value label: Moscow Regional Centre [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 5
status: not mapped

code Value label: Federal Republic of Germany [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 6
status: not mapped

code Value label: France [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 7
status: not mapped

code Value label: Argentina [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 8
status: not mapped

code Value label: Japan [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = 9
status: not mapped

code Value label: Unknown [OBSOLETE]
position: 008/20 (CONTINUING RESOURCES) = u
status: not mapped

code Value label: Other
position: 008/20 (CONTINUING RESOURCES) = z
status: not mapped

code Value label: Punched paper tape [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = g
status: not mapped

code Value label: Magnetic tape [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = h
status: not mapped

code Value label: Multimedia [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = i
status: not mapped

code Value label: Other physical medium [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = x
status: not mapped

code Value label: Other physical medium [OBSOLETE]
position: 008/22 (CONTINUING RESOURCES) = z
status: not mapped

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = z
status: not mapped

code Value label: No separate title page issued
position: 008/30 (CONTINUING RESOURCES) = #
status: not mapped

code Value label: No attempt to code
position: 008/30 (CONTINUING RESOURCES) = |
status: not mapped

code Value label: In last issue of volume, loose
position: 008/30 (CONTINUING RESOURCES) = a
status: not mapped

code Value label: In last issue of volume, attached
position: 008/30 (CONTINUING RESOURCES) = b
status: not mapped

code Value label: In first issue of next volume, loose
position: 008/30 (CONTINUING RESOURCES) = c
status: not mapped

code Value label: In first issue of next volume, attached
position: 008/30 (CONTINUING RESOURCES) = d
status: not mapped

code Value label: Published separately, free upon request
position: 008/30 (CONTINUING RESOURCES) = e
status: not mapped

code Value label: Published separately, free, automatically sent
position: 008/30 (CONTINUING RESOURCES) = f
status: not mapped

code Value label: Published separately, purchase, request
position: 008/30 (CONTINUING RESOURCES) = g
status: not mapped

code Value label: Unknown
position: 008/30 (CONTINUING RESOURCES) = u
status: not mapped

code Value label: Other title page availability
position: 008/30 (CONTINUING RESOURCES) = z
status: not mapped

code Value label: No index published
position: 008/31 (CONTINUING RESOURCES) = #
status: not mapped

code Value label: No attempt to code
position: 008/31 (CONTINUING RESOURCES) = |
status: not mapped

code Value label: Each issue contains index to its own contents (no volume index), loose
position: 008/31 (CONTINUING RESOURCES) = a
status: not mapped

code Value label: In last issue of volume, loose, separately paged
position: 008/31 (CONTINUING RESOURCES) = b
status: not mapped

code Value label: In last issue of volume, loose, unpaged
position: 008/31 (CONTINUING RESOURCES) = c
status: not mapped

code Value label: In last issue of volume, attached
position: 008/31 (CONTINUING RESOURCES) = d
status: not mapped

code Value label: In first issue of next volume, loose, separately paged
position: 008/31 (CONTINUING RESOURCES) = e
status: not mapped

code Value label: In first issue of next volume, loose, unpaged
position: 008/31 (CONTINUING RESOURCES) = f
status: not mapped

code Value label: In first issue of next volume, attached
position: 008/31 (CONTINUING RESOURCES) = g
status: not mapped

code Value label: Published separately, free, automatically sent
position: 008/31 (CONTINUING RESOURCES) = h
status: not mapped

code Value label: Published separately, free, upon request
position: 008/31 (CONTINUING RESOURCES) = i
status: not mapped

code Value label: Published separately, bound from publisher, free, automatically sent
position: 008/31 (CONTINUING RESOURCES) = j
status: not mapped

code Value label: Published separately, bound from publisher, free, upon request
position: 008/31 (CONTINUING RESOURCES) = k
status: not mapped

code Value label: Received separately, bound from publisher
position: 008/31 (CONTINUING RESOURCES) = l
status: not mapped

code Value label: Supplement or subseries, indexed in parent journal index
position: 008/31 (CONTINUING RESOURCES) = m
status: not mapped

code Value label: Unknown
position: 008/31 (CONTINUING RESOURCES) = u
status: not mapped

code Value label: Other index availability
position: 008/31 (CONTINUING RESOURCES) = z
status: not mapped

code Value label: No attempt to code
position: 008/32 (CONTINUING RESOURCES) = |
status: not mapped

code Value label: No cumulative index available
position: 008/32 (CONTINUING RESOURCES) = 0
status: not mapped

code Value label: Cumulative index available
position: 008/32 (CONTINUING RESOURCES) = 1
status: not mapped

code Value label: Unknown
position: 008/32 (CONTINUING RESOURCES) = u
status: not mapped

code Value label: Other [OBSOLETE]
position: 008/24 (MAPS) = h
status: not mapped

code Value label: Other
position: 008/24 (MAPS) = z
status: not mapped

code Value label:
position: 008/26-27 (MAPS) =
status: not mapped

code Value label:
position: 008/32 (MAPS) =
status: not mapped

code Value label: Film negative [OBSOLETE]
position: 008/33-34 (MAPS) = d
status: not mapped

code Value label: Facsimile [OBSOLETE]
position: 008/33-34 (MAPS) = f
status: not mapped

code Value label: Relief model [OBSOLETE]
position: 008/33-34 (MAPS) = g
status: not mapped

code Value label: Rare [OBSOLETE]
position: 008/33-34 (MAPS) = h
status: not mapped

code Value label: Braille [OBSOLETE]
position: 008/33-34 (MAPS) = m
status: not mapped

code Value label: Large print [OBSOLETE]
position: 008/33-34 (MAPS) = q
status: not mapped

code Value label: No case file exists
position: 008/30 (MIXED MATERIALS) = #
status: not mapped

code Value label: Case file exists
position: 008/30 (MIXED MATERIALS) = c
status: not mapped

code Value label: Collection not in library
position: 008/32 (MIXED MATERIALS) = a
status: not mapped

code Value label: Completely processed
position: 008/32 (MIXED MATERIALS) = b
status: not mapped

code Value label: Processed but with unprocessed additions
position: 008/32 (MIXED MATERIALS) = c
status: not mapped

code Value label: Requires processing
position: 008/32 (MIXED MATERIALS) = d
status: not mapped

code Value label: Totally unprocessed
position: 008/32 (MIXED MATERIALS) = e
status: not mapped

code Value label: Under total cloture
position: 008/32 (MIXED MATERIALS) = f
status: not mapped

code Value label: Unknown
position: 008/32 (MIXED MATERIALS) = u
status: not mapped

code Value label: Discrete grouping of material
position: 008/33 (MIXED MATERIALS) = a
status: not mapped

code Value label: Accession
position: 008/33 (MIXED MATERIALS) = b
status: not mapped

code Value label: Active solicitation
position: 008/33 (MIXED MATERIALS) = c
status: not mapped

code Value label: Solicitation unsuccessful
position: 008/33 (MIXED MATERIALS) = d
status: not mapped

code Value label: Information file only
position: 008/33 (MIXED MATERIALS) = e
status: not mapped

code Value label: Unknown
position: 008/33 (MIXED MATERIALS) = u
status: not mapped

code Value label: Control on collection level
position: 008/34 (MIXED MATERIALS) = a
status: not mapped

code Value label: Control by series
position: 008/34 (MIXED MATERIALS) = b
status: not mapped

code Value label: Control by container
position: 008/34 (MIXED MATERIALS) = c
status: not mapped

code Value label: Control by folder
position: 008/34 (MIXED MATERIALS) = d
status: not mapped

code Value label: Control by item
position: 008/34 (MIXED MATERIALS) = e
status: not mapped

code Value label: Unknown
position: 008/34 (MIXED MATERIALS) = u
status: not mapped

code Value label: No parts exist
position: 008/21 (MUSIC) = #
status: not mapped

code Value label: Parts exist
position: 008/21 (MUSIC) = a
status: not mapped

code Value label: Not applicable
position: 008/21 (MUSIC) = n
status: not mapped

code Value label: Unknown
position: 008/21 (MUSIC) = u
status: not mapped

code Value label: Multimedia [OBSOLETE]
position: 008/23 (MUSIC) = i
status: not mapped

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (MUSIC) = x
status: not mapped

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (MUSIC) = z
status: not mapped

code Value label: Historical information other than music [OBSOLETE]
position: 008/24-29 (MUSIC) = j
status: not mapped

code Value label: Not applicable [OBSOLETE]
position: 008/24-29 (MUSIC) = n
status: not mapped

code Value label: No attempt to code
position: 008/32 (MUSIC) = |
status: not mapped

code Value label: Main entry not in body of entry
position: 008/32 (MUSIC) = 0
status: not mapped

code Value label: Main entry in body of entry
position: 008/32 (MUSIC) = 1
status: not mapped

code Value label: Not in LC
position: 008/21 (VISUAL MATERIALS) = #
status: not mapped

code Value label: In LC, print note
position: 008/21 (VISUAL MATERIALS) = a
status: not mapped

code Value label: In LC, do not print note
position: 008/21 (VISUAL MATERIALS) = b
status: not mapped

code Value label: Unknown
position: 008/21 (VISUAL MATERIALS) = u
status: not mapped

code Value label: No accompanying matter
position: 008/23-27 (VISUAL MATERIALS) = #
status: not mapped

code Value label: No attempt to code
position: 008/23-27 (VISUAL MATERIALS) = |
status: not mapped

code Value label: No [OBSOLETE]
position: 008/23-27 (VISUAL MATERIALS) = 0
status: not mapped

code Value label: Yes [OBSOLETE]
position: 008/23-27 (VISUAL MATERIALS) = 1
status: not mapped

code Value label: Stills
position: 008/23-27 (VISUAL MATERIALS) = l
status: not mapped

code Value label: Script material
position: 008/23-27 (VISUAL MATERIALS) = m
status: not mapped

code Value label: Posters
position: 008/23-27 (VISUAL MATERIALS) = o
status: not mapped

code Value label: Pressbooks
position: 008/23-27 (VISUAL MATERIALS) = p
status: not mapped

code Value label: Lobby cards
position: 008/23-27 (VISUAL MATERIALS) = q
status: not mapped

code Value label: Instructional materials
position: 008/23-27 (VISUAL MATERIALS) = r
status: not mapped

code Value label: Music
position: 008/23-27 (VISUAL MATERIALS) = s
status: not mapped

code Value label: Other
position: 008/23-27 (VISUAL MATERIALS) = z
status: not mapped

code Value label: No attempt to code
position: 008/32 (VISUAL MATERIALS) = |
status: not mapped

code Value label: Main entry not in body of entry
position: 008/32 (VISUAL MATERIALS) = 0
status: not mapped

code Value label: Main entry in body of entry
position: 008/32 (VISUAL MATERIALS) = 1
status: not mapped

code Value label: Electronic videorecording [OBSOLETE]
position: 008/33 (VISUAL MATERIALS) = e
status: not mapped

code Value label: Not applicable [OBSOLETE]
position: 008/34 (VISUAL MATERIALS) = #
status: not mapped

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (BOOKS) = g
status: reviewed

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (BOOKS) = g
status: reviewed

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (BOOKS) = h
status: reviewed

code Value label: Multimedia [OBSOLETE]
position: 008/23 (BOOKS) = i
status: reviewed

code Value label: Other form of reproduction [OBSOLETE]
position: 008/23 (BOOKS) = z
status: reviewed

code Value label: Handbooks [OBSOLETE]
position: 008/24-27 (BOOKS) = h
status: reviewed

code Value label: Technical reports [OBSOLETE]
position: 008/24-27 (BOOKS) = x
status: reviewed

code Value label: Government publication--level undetermined [OBSOLETE]
position: 008/28 (BOOKS) = n
status: reviewed

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = g
status: reviewed

code Value label: Punched paper tape [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = g
status: reviewed

code Value label: Magnetic tape [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = h
status: reviewed

code Value label: Multimedia [OBSOLETE]
position: 008/23 (CONTINUING RESOURCES) = i
status: reviewed

code Value label: Technical reports [OBSOLETE]
position: 008/25-27 (CONTINUING RESOURCES) = x
status: reviewed

code Value label: Government publication--level undetermined [OBSOLETE]
position: 008/28 (CONTINUING RESOURCES) = n
status: reviewed

code Value label: Color [OBSOLETE]
position: 008/18-21 (MAPS) = h
status: reviewed

code Value label: Prime meridian not specified
position: 008/24 (MAPS) = #
status: reviewed

code Value label: Greenwich
position: 008/24 (MAPS) = e
status: reviewed

code Value label: Ferro
position: 008/24 (MAPS) = f
status: reviewed

code Value label: Paris
position: 008/24 (MAPS) = g
status: reviewed

code Value label: Philadelphia
position: 008/24 (MAPS) = p
status: reviewed

code Value label: Washington, D.C.
position: 008/24 (MAPS) = w
status: reviewed

code Value label: Photocopy, blue line print [OBSOLETE]
position: 008/33-34 (MAPS) = a
status: reviewed

code Value label: Photocopy [OBSOLETE]
position: 008/33-34 (MAPS) = b
status: reviewed #

**Comment by gerontakos** [comment]
If you were working with the old list, then your world just got a bit more complicated! (Due to my processing error.)
________________________________

**Comment by gerontakos** [comment]
DONE!
