### ISSUE TITLE
To Do List 2023-07-20 (this IS an issue)

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd_vocabs_marc_006_008#9]
1. ~~TG: extract obsolete values we use from spreadsheets; give to DKT~~
    1a. DKT will make sure they are present in the 008 vocabs
        1ai. ~~enter 8 values that were missing.~~
        **1aii. enter values that have no home vocabulary
              1aii1. create as many vocabularies as needed**

2. ~~Prov statement~~
    ~~2a. DKT proof the statement and edit as needed.~~
   ~~2b. Theo create the web document and complete the DOI~~
    ~~2c. TG insert into the conceptScheme data using dct:provenance~~
    ~~2d. store in Githud, uwlswd/datasets~~

3. ~~Change conceptScheme titles (DKT) -- see [issue 4](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/issues/4)~~
     ~~3a. Follow issue #4~~
     ~~3b. DKT is empowered to make decisions on this~~

4. ~~Add 2 dct:source triples to every ConceptSchem,e (follow issue #3)(TG) -- see [issue 3](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/issues/3)~~

5. ~~Enter an alternative title in every concept scheme that describes the source vocabulary (DKT)~~
   ~~5a. Like this:
<doi> dct:alternative "MARC21 008/28-29 values expressed using RDF"~~

6. ~~TG Write little script: -- see [issue 2](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/issues/2)~~
    ~~6a. Remove skos:exactMatch triples from all concept descriptions (TG)~~
    ~~6b. Remove all //skos:Concept @xml:lang="en" (TG)~~

7. DOIs
📢  see full workflow "pipline" in [issue 7](https://github.com/uwlib-cams/uwlswd_vocabs_marc_006_008/issues/7)
    7a. ~~Initiate a draft DOI (Theo will do 2 on his own then sit down with DKYT and do like 5 together; then maybe DKT can do the remaining 16)~~
    7b. ~~DataCite XML metadata--create in oXygen~~

8. ~~Transfer 6 vocabularies from 007 (2 in Visual Materials, 4 in Music) to 008.~~
    8a. ~~Issue: They are copied into 008, but missing the history from 007.~~

**Comment by dkreisstomkins** [comment]
Re: #5 
Some vocabularies will have the same alternative title.  Is this ok?

Example: both Computer Files and Some/Common vocabulary sets have a vocabulary numbered 23, which means both will have
      <dct:alternative>MARC21 008/23 values expressed using RDF</dct:alternative>
as their entry, without anything differentiating the two concept schemes in this line.

**Comment by gerontakos** [comment]
All done!
